In [1]:
pwd

'/mmfs1/data/bergerar/BC-sim/Code'

In [1]:
import pandas as pd
import numpy as np
from numpy import load
from numpy import savetxt

### saving npy as csv - adhd

In [15]:
adhd_data = load('../../BC-sim/synth-data-01/tx_log_adhd1.npy')
adhd_data

array([[12.83448928, 10.03501401],
       [11.01158119, 11.31620783],
       [12.60649909, 14.64377114],
       [10.8690737 , 13.48263603],
       [ 6.15908197,  6.33734945],
       [11.35469031, 11.88888342],
       [12.5873878 , 10.74266579],
       [ 7.27042151,  9.1562977 ],
       [14.05133409, 12.21669232],
       [11.86751549, 13.22217728],
       [13.3038691 , 14.72231178],
       [13.14993766, 14.29322316],
       [ 8.73766182,  9.25387713],
       [ 7.24498077,  9.10661222],
       [10.72792999, 10.23429154],
       [ 6.41064931,  5.24445804],
       [ 5.79983778,  2.85213562],
       [ 9.21622922,  9.53472706],
       [ 6.49946053,  6.10264614],
       [14.09831201, 16.03187816],
       [14.51438413, 16.70575769],
       [ 7.51895692,  9.99252697],
       [ 5.06456408,  5.3614429 ],
       [ 6.18925087,  7.45991521],
       [ 9.42146579, 11.7025752 ],
       [13.16916458, 11.35833811],
       [11.19138018, 13.04290617],
       [ 8.84429772,  7.03773284],
       [ 5.67143673,

In [4]:
print(type(adhd_data))

<class 'numpy.ndarray'>


In [6]:
savetxt('tx_log_adhd1.csv', adhd_data, delimiter=',')

In [9]:
file = pd.read_csv('../../BC-sim/synth-data-01/tx_log_adhd1.csv')
print("\nOriginal file:")
print(file)

# adding header
headerList = ['Sphere 1', 'Sphere 2']
  
# converting data frame to csv
file.to_csv('tx_log_adhd1.csv', header=headerList, index=False)
  
# display modified csv file
file2 = pd.read_csv('tx_log_adhd1.csv')
print('\nModified file:')
print(file2)


Original file:
     1.283448927529020267e+01  1.003501400783719077e+01
0                   11.011581                 11.316208
1                   12.606499                 14.643771
2                   10.869074                 13.482636
3                    6.159082                  6.337349
4                   11.354690                 11.888883
..                        ...                       ...
494                  7.543617                  9.531810
495                 12.901628                 10.921605
496                  5.062251                  3.099718
497                 14.173622                 13.385439
498                 10.600703                 12.911430

[499 rows x 2 columns]

Modified file:
      Sphere 1   Sphere 2
0    11.011581  11.316208
1    12.606499  14.643771
2    10.869074  13.482636
3     6.159082   6.337349
4    11.354690  11.888883
..         ...        ...
494   7.543617   9.531810
495  12.901628  10.921605
496   5.062251   3.099718
497  14.1736

In [35]:
df2 = file2
df2

Sphere 1   Sphere 2
0    11.011581  11.316208
1    12.606499  14.643771
2    10.869074  13.482636
3     6.159082   6.337349
4    11.354690  11.888883
..         ...        ...
494   7.543617   9.531810
495  12.901628  10.921605
496   5.062251   3.099718
497  14.173622  13.385439
498  10.600703  12.911430

[499 rows x 2 columns]

In [25]:
data = load('../../BC-sim/synth-data-01/tx_log_adhd1.npy')
data
new = data[0:1]
print(new)
print(new.shape)

[[12.83448928 10.03501401]]
(1, 2)


In [36]:
new_row = pd.DataFrame({'Sphere 1': new[0,0], 'Sphere 2': new[0,1]}, index=[0])
df_fix = pd.concat([new_row,df2.loc[:]]).reset_index(drop=True)
print (df_fix)

      Sphere 1   Sphere 2
0    12.834489  10.035014
1    11.011581  11.316208
2    12.606499  14.643771
3    10.869074  13.482636
4     6.159082   6.337349
..         ...        ...
495   7.543617   9.531810
496  12.901628  10.921605
497   5.062251   3.099718
498  14.173622  13.385439
499  10.600703  12.911430

[500 rows x 2 columns]


In [37]:
df_fix #YAY

Sphere 1   Sphere 2
0    12.834489  10.035014
1    11.011581  11.316208
2    12.606499  14.643771
3    10.869074  13.482636
4     6.159082   6.337349
..         ...        ...
495   7.543617   9.531810
496  12.901628  10.921605
497   5.062251   3.099718
498  14.173622  13.385439
499  10.600703  12.911430

[500 rows x 2 columns]

In [38]:
df_fix.to_csv('../../BC-sim/tx_log_adhd.csv') #success -- all values and headers accounted forrrr

### saving npy as csv - td

In [39]:
td_data = load('../../BC-sim/synth-data-01/tx_log_td1.npy')
td_data

array([[24.63645822, 20.59275331],
       [15.94599213, 12.21205229],
       [19.40191027, 15.01630668],
       [31.73753169, 26.81225647],
       [24.53352722, 25.96277627],
       [21.82176365, 26.12255411],
       [29.16702235, 30.69535279],
       [26.21536476, 25.01159564],
       [11.15825468,  9.67803879],
       [25.2572582 , 28.92528302],
       [10.85860164, 12.53455265],
       [12.22810868, 13.93616227],
       [13.00969368, 16.02301376],
       [25.05030174, 24.2964054 ],
       [23.24249294, 26.47739743],
       [14.70899859, 17.24640045],
       [19.30052074, 15.49852781],
       [33.39113408, 36.83792164],
       [23.90775396, 24.66002208],
       [30.88903323, 27.67932439],
       [16.27060293, 17.33398576],
       [13.99040779, 15.98876919],
       [29.4930752 , 28.77474057],
       [29.30996736, 26.23147901],
       [20.19161366, 15.93035687],
       [13.83207299, 14.88946151],
       [15.68104851, 15.59498698],
       [18.56326142, 21.97597008],
       [27.47640093,

In [40]:
print(type(td_data))

<class 'numpy.ndarray'>


In [41]:
savetxt('tx_log_td1.csv', td_data, delimiter=',')

In [42]:
file = pd.read_csv('../../BC-sim/synth-data-01/tx_log_td1.csv')
print("\nOriginal file:")
print(file)

# adding header
headerList = ['Sphere 1', 'Sphere 2']
  
# converting data frame to csv
file.to_csv('tx_log_td1.csv', header=headerList, index=False)
  
# display modified csv file
file2 = pd.read_csv('tx_log_td1.csv')
print('\nModified file:')
print(file2)


Original file:
     2.463645821550618464e+01  2.059275330558605077e+01
0                   15.945992                 12.212052
1                   19.401910                 15.016307
2                   31.737532                 26.812256
3                   24.533527                 25.962776
4                   21.821764                 26.122554
..                        ...                       ...
494                 29.806246                 31.775410
495                 14.683680                 13.065503
496                 18.065294                 13.891190
497                 14.391185                 19.336634
498                 12.440938                  8.076007

[499 rows x 2 columns]

Modified file:
      Sphere 1   Sphere 2
0    15.945992  12.212052
1    19.401910  15.016307
2    31.737532  26.812256
3    24.533527  25.962776
4    21.821764  26.122554
..         ...        ...
494  29.806246  31.775410
495  14.683680  13.065503
496  18.065294  13.891190
497  14.3911

In [43]:
df2 = file2
df2

Sphere 1   Sphere 2
0    15.945992  12.212052
1    19.401910  15.016307
2    31.737532  26.812256
3    24.533527  25.962776
4    21.821764  26.122554
..         ...        ...
494  29.806246  31.775410
495  14.683680  13.065503
496  18.065294  13.891190
497  14.391185  19.336634
498  12.440938   8.076007

[499 rows x 2 columns]

In [44]:
data = load('../../BC-sim/synth-data-01/tx_log_td1.npy')
data
new = data[0:1]
print(new)
print(new.shape)

[[24.63645822 20.59275331]]
(1, 2)


In [48]:
new_row = pd.DataFrame({'Sphere 1': new[0,0], 'Sphere 2': new[0,1]}, index=[0])
df_fix2 = pd.concat([new_row,df2.loc[:]]).reset_index(drop=True)
print (df_fix2)

      Sphere 1   Sphere 2
0    24.636458  20.592753
1    15.945992  12.212052
2    19.401910  15.016307
3    31.737532  26.812256
4    24.533527  25.962776
..         ...        ...
495  29.806246  31.775410
496  14.683680  13.065503
497  18.065294  13.891190
498  14.391185  19.336634
499  12.440938   8.076007

[500 rows x 2 columns]


In [49]:
df_fix2 #YAY

Sphere 1   Sphere 2
0    24.636458  20.592753
1    15.945992  12.212052
2    19.401910  15.016307
3    31.737532  26.812256
4    24.533527  25.962776
..         ...        ...
495  29.806246  31.775410
496  14.683680  13.065503
497  18.065294  13.891190
498  14.391185  19.336634
499  12.440938   8.076007

[500 rows x 2 columns]

In [47]:
df_fix2.to_csv('../../BC-sim/tx_log_td.csv') #success -- all values and headers accounted forrrr

### combine csvs

In [51]:
frames = [df_fix, df_fix2]
  
result = pd.concat(frames)
display(result)

Sphere 1   Sphere 2
0    24.636458  20.592753
1    15.945992  12.212052
2    19.401910  15.016307
3    31.737532  26.812256
4    24.533527  25.962776
..         ...        ...
495  29.806246  31.775410
496  14.683680  13.065503
497  18.065294  13.891190
498  14.391185  19.336634
499  12.440938   8.076007

[1000 rows x 2 columns]

In [53]:
result.to_csv('tx_log_adhd_and_td.csv')

In [2]:
stuff = pd.read_csv('../../BC-sim/synth-data-01/sim_all.csv')
stuff

Unnamed: 0  Index  Sub   Sphere 1   Sphere 2  DX
0             0      0    0  12.834489  10.035014   1
1             1      1    1  11.011581  11.316208   1
2             2      2    2  12.606499  14.643771   1
3             3      3    3  10.869074  13.482636   1
4             4      4    4   6.159082   6.337349   1
..          ...    ...  ...        ...        ...  ..
995         495    995  495  29.806246  31.775410   0
996         496    996  496  14.683680  13.065503   0
997         497    997  497  18.065294  13.891190   0
998         498    998  498  14.391185  19.336634   0
999         499    999  499  12.440938   8.076007   0

[1000 rows x 6 columns]

In [3]:
stuff.drop('Unnamed: 0', inplace=True, axis=1)
stuff

Index  Sub   Sphere 1   Sphere 2  DX
0        0    0  12.834489  10.035014   1
1        1    1  11.011581  11.316208   1
2        2    2  12.606499  14.643771   1
3        3    3  10.869074  13.482636   1
4        4    4   6.159082   6.337349   1
..     ...  ...        ...        ...  ..
995    995  495  29.806246  31.775410   0
996    996  496  14.683680  13.065503   0
997    997  497  18.065294  13.891190   0
998    998  498  14.391185  19.336634   0
999    999  499  12.440938   8.076007   0

[1000 rows x 5 columns]

In [4]:
stuff['Deformation'] = stuff['Sphere 2'] - stuff['Sphere 1']

In [5]:
stuff

Index  Sub   Sphere 1   Sphere 2  DX  Deformation
0        0    0  12.834489  10.035014   1    -2.799475
1        1    1  11.011581  11.316208   1     0.304627
2        2    2  12.606499  14.643771   1     2.037272
3        3    3  10.869074  13.482636   1     2.613562
4        4    4   6.159082   6.337349   1     0.178267
..     ...  ...        ...        ...  ..          ...
995    995  495  29.806246  31.775410   0     1.969164
996    996  496  14.683680  13.065503   0    -1.618177
997    997  497  18.065294  13.891190   0    -4.174104
998    998  498  14.391185  19.336634   0     4.945449
999    999  499  12.440938   8.076007   0    -4.364931

[1000 rows x 6 columns]

In [8]:
stuff.to_csv('sim_all_def.csv')

In [14]:
stuff = pd.read_csv('../../BC-sim/synth-data-01/sim_all.csv')
stuff

Unnamed: 0  Index  Sub   Sphere 1   Sphere 2  DX
0             0      0    0  12.834489  10.035014   1
1             1      1    1  11.011581  11.316208   1
2             2      2    2  12.606499  14.643771   1
3             3      3    3  10.869074  13.482636   1
4             4      4    4   6.159082   6.337349   1
..          ...    ...  ...        ...        ...  ..
995         495    995  495  29.806246  31.775410   0
996         496    996  496  14.683680  13.065503   0
997         497    997  497  18.065294  13.891190   0
998         498    998  498  14.391185  19.336634   0
999         499    999  499  12.440938   8.076007   0

[1000 rows x 6 columns]

In [15]:
stuff.drop('Unnamed: 0', inplace=True, axis=1)
stuff

Index  Sub   Sphere 1   Sphere 2  DX
0        0    0  12.834489  10.035014   1
1        1    1  11.011581  11.316208   1
2        2    2  12.606499  14.643771   1
3        3    3  10.869074  13.482636   1
4        4    4   6.159082   6.337349   1
..     ...  ...        ...        ...  ..
995    995  495  29.806246  31.775410   0
996    996  496  14.683680  13.065503   0
997    997  497  18.065294  13.891190   0
998    998  498  14.391185  19.336634   0
999    999  499  12.440938   8.076007   0

[1000 rows x 5 columns]

In [16]:
stuff['S Deformation'] =  stuff['Sphere 2'] - stuff['Sphere 1'] # s or specific deformation 
stuff

Index  Sub   Sphere 1   Sphere 2  DX  S Deformation
0        0    0  12.834489  10.035014   1      -2.799475
1        1    1  11.011581  11.316208   1       0.304627
2        2    2  12.606499  14.643771   1       2.037272
3        3    3  10.869074  13.482636   1       2.613562
4        4    4   6.159082   6.337349   1       0.178267
..     ...  ...        ...        ...  ..            ...
995    995  495  29.806246  31.775410   0       1.969164
996    996  496  14.683680  13.065503   0      -1.618177
997    997  497  18.065294  13.891190   0      -4.174104
998    998  498  14.391185  19.336634   0       4.945449
999    999  499  12.440938   8.076007   0      -4.364931

[1000 rows x 6 columns]

In [17]:
stuff['S Deformation'].iloc[500:1000] = 0
stuff

<ipython-input-17-b8287f9e9b01>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stuff['S Deformation'].iloc[500:1000] = 0


Index  Sub   Sphere 1   Sphere 2  DX  S Deformation
0        0    0  12.834489  10.035014   1      -2.799475
1        1    1  11.011581  11.316208   1       0.304627
2        2    2  12.606499  14.643771   1       2.037272
3        3    3  10.869074  13.482636   1       2.613562
4        4    4   6.159082   6.337349   1       0.178267
..     ...  ...        ...        ...  ..            ...
995    995  495  29.806246  31.775410   0       0.000000
996    996  496  14.683680  13.065503   0       0.000000
997    997  497  18.065294  13.891190   0       0.000000
998    998  498  14.391185  19.336634   0       0.000000
999    999  499  12.440938   8.076007   0       0.000000

[1000 rows x 6 columns]

In [18]:
zarray = np.array(stuff['Sphere 2'] - stuff['Sphere 1'])
zarray

array([-2.79947527e+00,  3.04626639e-01,  2.03727205e+00,  2.61356233e+00,
        1.78267483e-01,  5.34193114e-01, -1.84472201e+00,  1.88587619e+00,
       -1.83464177e+00,  1.35466179e+00,  1.41844268e+00,  1.14328550e+00,
        5.16215306e-01,  1.86163145e+00, -4.93638446e-01, -1.16619127e+00,
       -2.94770216e+00,  3.18497849e-01, -3.96814393e-01,  1.93356615e+00,
        2.19137355e+00,  2.47357005e+00,  2.96878820e-01,  1.27066434e+00,
        2.28110940e+00, -1.81082647e+00,  1.85152599e+00, -1.80656489e+00,
        1.80041686e+00, -1.14491400e+00,  6.91331783e-01, -9.52080085e-01,
        6.28002579e-01, -6.26727700e-01, -1.15082105e+00, -2.93080445e+00,
       -1.34884795e+00, -2.45540040e+00, -6.35458544e-01,  1.79316328e-01,
       -1.74709229e+00,  8.36895151e-01,  1.61844281e+00, -1.04462509e+00,
       -1.64994255e+00, -1.36333860e+00, -2.24991411e+00, -5.11750066e-01,
        1.30366083e+00, -9.60272562e-01,  1.03042294e+00, -1.04385548e+00,
       -1.72097930e+00, -

In [19]:
newz = zarray[500:1000]
newz

array([-4.04370491, -3.73393984, -4.38560359, -4.92527523,  1.42924905,
        4.30079046,  1.52833043, -1.20376912, -1.48021589,  3.66802482,
        1.67595101,  1.7080536 ,  3.01332007, -0.75389634,  3.23490449,
        2.53740186, -3.80199293,  3.44678755,  0.75226812, -3.20970884,
        1.06338283,  1.99836141, -0.71833463, -3.07848836, -4.26125679,
        1.05738852, -0.08606152,  3.41270866,  3.68033229,  2.01875627,
       -2.97384691,  3.50763305, -4.79792747,  4.59068652,  3.49982417,
        4.15274   ,  2.74885436, -1.36128744,  3.13379344, -1.3442818 ,
        4.27292509,  4.85317037, -1.80420255, -3.05723312,  0.11966433,
       -1.7449092 , -2.79001141, -4.60025238, -2.45808939,  3.48966798,
       -2.05021488,  4.84468482,  4.87865736, -3.22108005,  0.4431636 ,
        0.36387924,  1.9438954 , -2.54386161,  1.42293397,  2.65276553,
       -1.8399532 , -2.57725644, -2.22862402, -0.55212659,  1.38246452,
        2.66920504,  2.64866073, -0.90648468, -2.10014238,  0.32

In [20]:
newz.shape

(500,)

In [21]:
arr = np.concatenate((newz, newz))
print(arr.shape)

(1000,)


In [22]:
stuff['Z Deformation'] = arr
stuff

Index  Sub   Sphere 1   Sphere 2  DX  S Deformation  Z Deformation
0        0    0  12.834489  10.035014   1      -2.799475      -4.043705
1        1    1  11.011581  11.316208   1       0.304627      -3.733940
2        2    2  12.606499  14.643771   1       2.037272      -4.385604
3        3    3  10.869074  13.482636   1       2.613562      -4.925275
4        4    4   6.159082   6.337349   1       0.178267       1.429249
..     ...  ...        ...        ...  ..            ...            ...
995    995  495  29.806246  31.775410   0       0.000000       1.969164
996    996  496  14.683680  13.065503   0       0.000000      -1.618177
997    997  497  18.065294  13.891190   0       0.000000      -4.174104
998    998  498  14.391185  19.336634   0       0.000000       4.945449
999    999  499  12.440938   8.076007   0       0.000000      -4.364931

[1000 rows x 7 columns]

In [23]:
stuff.to_csv('sim_all_def.csv')